project:
  type: website
  output-dir: docs

website:
  title: "Biostatistics for Health Sciences - VTPEH 6105 / 6270"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "VTPEH 6105"
        contents:
          - text: "Course Information"
            href: index.qmd
          - text: "Syllabus"
            href: syllabus.qmd
          - text: "Class Schedule"
            href: schedule.qmd
          - section: "Workshops"
            contents:
              - text: "Workshop 01 - R Bootcamp Part I"
                href: "Classes-selected (1)/01-23 - Workshop 01 - R Bootcamp Part I/VTPEH6105-WS01-R-Bootcamp-Part-I.html"
              - text: "Workshop 02 - R Bootcamp Part II"
                href: "Classes-selected (1)/01-30 - Workshop 02 - R Bootcamp Part II/VTPEH6105-WS02-R-Bootcamp-Part-II.html"
              - text: "Workshop 03 - Comparison of Means"
                href: "Classes-selected (1)/02-13 - Workshop 04 - Comparison of Means/VTPEH6105-WS04-Mean-Comparison.html"
              - text: "Workshop 04 - Comparison of Means across Multiple Groups (ANOVA)"
                href: "02-20 - Workshop 05 - Comparison of Means across Multiple Groups/VTPEH6105-WS05-ANOVAs.html"
              - text: "Workshop 05 - Comparison of Prevalences"
                href: "02-27 - Workshop 06 - Comparison of Prevalences/VTPEH6105-WS06-Comparison-of-Prevalences.html"
              - text: "Workshop 06 - Linear Regressions"
                href: "03-06 - Workshop 07 - Linear Regressions/VTPEH6105-WS07-Linear-Regressions.html"
              - text: "Workshop 07 - Rates and Standardization"
                href: "03-13 - Workshop 08 - Rates and Standardization/VTPEH6105 - Workshop 08 - Rates and Standardization.docx"
              - text: "Workshop 08 - Multivariate Models"
                href: "03-20 - Workshop 09 - Multivariate Models/VTPEH6105-WS09-Multivariate-Model.html"
              - text: "Workshop 09 - Logistic Regressions"
                href: "03-27 - Workshop 10 - Logistic Regressions/VTPEH6105-WS10-Logistic-Regressions.html"
      - section: "VTPEH 6270"
        contents:
          - text: "Overview"
            href: 6270/index.qmd
          - text: "Assignments"
            href: 6270/assignments.qmd
          - text: "Workshops"
            href: 6270/workshops.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true