project:
  type: website
  output-dir: docs

website:
  title: "Biostatistics for Health Sciences - VTPEH 6105"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Course Information"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Class Schedule"
        href: schedule.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
