project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "6105/**/*.qmd"
    - "6270/**/*.qmd"
  resources:
    - Workshops/**

website:
  title: "Cornell MPH Biostatistics"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "VTPEH 6105"
        href: 6105/index.qmd
      - text: "VTPEH 6270"
        href: 6270/6270/index.qmd
  sidebar:
    - id: home
      title: " "
      style: "docked"
      contents:
        - text: "Home"
          href: index.qmd
    - id: vtpeh-6105
      title: "VTPEH 6105"
      style: "docked"
      search: true
      contents:
        - text: "Course Information"
          href: 6105/index.qmd
        - text: "Syllabus & Schedule"
          href: 6105/syllabus.qmd
    - id: vtpeh-6270
      title: "VTPEH 6270"
      style: "docked"
      search: true
      contents:
        - text: "Overview"
          href: 6270/6270/index.qmd
        - text: "Assignments"
          href: 6270/6270/6270/assignments.qmd
        - text: "Workshops"
          href: 6270/6270/6270/workshops.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    code-copy: true
    link-external-newwindow: true
